#ifndef IMMIX_CONSTANTS_H
#define IMMIX_CONSTANTS_H

#define OBJ_ALIGN_BITS 3
#define OBJ_ALIGN (1 << OBJ_ALIGN_BITS)

#define OBJ_ALIGN_INVERSE_MASK (~((uintptr_t)OBJ_ALIGN - 1))

#define BLOCK_SIZE_BITS 15
#define LINE_SIZE_BITS 8

#define BLOCK_METADATA_SIZE_BITS 3
#define LINE_METADATA_SIZE_BITS 0

#define BLOCK_TOTAL_SIZE (1 << BLOCK_SIZE_BITS)
#define BLOCK_METADATA_SIZE (1 << BLOCK_METADATA_SIZE_BITS)
#define LINE_SIZE (1UL << LINE_SIZE_BITS)
#define LINE_METADATA_SIZE (1 << LINE_METADATA_SIZE_BITS)

#define LINE_SIZE_MASK (LINE_SIZE - 1)

#define OBJECT_HEADER_SIZE 8
#define OBJECT_HEADER_SLOTS (OBJECT_HEADER_SIZE / OBJ_ALIGN)

#define LINE_COUNT                                                             \
    ((BLOCK_TOTAL_SIZE - BLOCK_METADATA_SIZE) /                                \
     (LINE_SIZE + LINE_METADATA_SIZE))

#define TOTAL_BLOCK_METADATA_SIZE                                              \
    (BLOCK_METADATA_SIZE + (LINE_COUNT * LINE_METADATA_SIZE))

#define BLOCK_METADATA_ALIGNED_SIZE                                            \
    ((TOTAL_BLOCK_METADATA_SIZE + LINE_SIZE - 1) / LINE_SIZE * LINE_SIZE)

#define SLOTS_IN_LINE (LINE_SIZE / OBJ_ALIGN)
#define SLOTS_IN_BLOCK (BLOCK_TOTAL_SIZE / OBJ_ALIGN)

#define BLOCK_SIZE_IN_BYTES_MASK (BLOCK_TOTAL_SIZE - 1)
#define BLOCK_SIZE_IN_BYTES_INVERSE_MASK (~BLOCK_SIZE_IN_BYTES_MASK)

#define LARGE_BLOCK_SIZE_BITS 13
#define LARGE_BLOCK_SIZE (1 << LARGE_BLOCK_SIZE_BITS)

#define LARGE_OBJECT_MIN_SIZE_BITS 13
#define LARGE_OBJECT_MAX_SIZE_BITS 34

#define MIN_BLOCK_SIZE (1UL << LARGE_OBJECT_MIN_SIZE_BITS)
#define MAX_BLOCK_SIZE (1UL << LARGE_OBJECT_MAX_SIZE_BITS)

#define LARGE_BLOCK_MASK (~((1 << LARGE_OBJECT_MIN_SIZE_BITS) - 1))

#define GROWTH_RATE 30

#endif // IMMIX_CONSTANTS_H
